In [3]:
from glob import glob
import pandas as pd

In [4]:
contribs = pd.read_csv("raw_contributions/COS2.csv")
party_lookup = {
    "D)": "democrat",
    "R)": "republican"
}
def extract_contrib(row):
    firstname = row["FirstLastP"].split(" ")[0].lower()
    lastname = row["FirstLastP"].split(" ")[1].lower()
    party = row["FirstLastP"].split("(")[1]
    party = party_lookup.get(party, "other")
    individual = row["Indivs"]
    pac = row["Pacs"]
    total = row["Total"]
    contributor = row["Contrib"]
    
    return pd.Series({
        "firstname": firstname,
        "lastname": lastname,
        "party": party,
        "total": total,
        "individual": individual,
        "pac": pac,
        "contributor": contributor
        })
processed_contribs = contribs.apply(extract_contrib, axis=1)
file = "raw_contributions/COS2.csv"
race = file.split("/")[-1].split(".")[0]
processed_contribs = processed_contribs.assign(race=race)

In [5]:
contribs

,affiliateid,orgid,pacid,cycle,CID,FirstLastP,Contrib,Indivs,Pacs,Total,Rank,CRPICO,ReleaseDate,NetRcpts
0,NaN,D000065181,NaN,2020,N00030780,Cory Gardner (R),Votesane PAC,124600,0,124600,1,I,2021-03-22 00:00:00 +0000,28075080.77
1,NaN,D000021845,NaN,2020,N00030780,Cory Gardner (R),Apollo Global Management,52461,12500,64961,2,I,2021-03-22 00:00:00 +0000,28075080.77
2,NaN,D000022003,NaN,2020,N00030780,Cory Gardner (R),GEO Group,55979,0,55979,3,I,2021-03-22 00:00:00 +0000,28075080.77
3,NaN,D000000109,NaN,2020,N00030780,Cory Gardner (R),Blue Cross/Blue Shield,35765,16000,51765,4,I,2021-03-22 00:00:00 +0000,28075080.77
4,NaN,D000021873,NaN,2020,N00030780,Cory Gardner (R),Blackstone Group,50788,0,50788,5,I,2021-03-22 00:00:00 +0000,28075080.77
5,NaN,D000021972,NaN,2020,N00030780,Cory Gardner (R),Elliott Management,44700,0,44700,6,I,2021-03-22 00:00:00 +0000,28075080.77
6,NaN,D000021679,NaN,2020,N00030780,Cory Gardner (R),BGR Group,36300,6366,42666,7,I,2021-03-22 00:00:00 +0000,28075080.77
7,NaN,D000000321,NaN,2020,N00030780,Cory Gardner (R),NextEra Energy,29554,5000,34554,8,I,2021-03-22 00:00:00 +0000,28075080.77
8,NaN,D000000724,NaN,2020,N00030780,Cory Gardner (R),"Brownstein, Hyatt et al",26413,8000,34413,9,I,2021-03-22 00:00:00 +0000,28075080.77
9,NaN,D000000769,NaN,2020,N00030780,Cory Gardner (R),"Paul, Weiss et al",34275,0,34275,10,I,2021-03-22 00:00:00 +0000,28075080.77
10,NaN,NaN,NaN,2020,N00030780,Cory Gardner (R),Lmbi Lp,33600,0,33600,11,I,2021-03-22 00:00:00 +0000,28075080.77
11,NaN,D000029689,NaN,2020,N00030780,Cory Gardner (R),Visa Inc,23105,10000,33105,12,I,2021-03-22 00:00:00 +0000,28075080.77
12,NaN,D000000535,NaN,2020,N00030780,Cory Gardner (R),DISH Network,31562,0,31562,13,I,2021-03-22 00:00:00 +0000,28075080.77
13,NaN,D000000131,NaN,2020,N00030780,Cory Gardner (R),Deloitte LLP,20548,10000,30548,14,I,2021-03-22 00:00:00 +0000,28075080.77
14,NaN,D000066716,NaN,2020,N00030780,Cory Gardner (R),Rock Holdings,29645,0,29645,15,I,2021-03-22 00:00:00 +0000,28075080.77
15,NaN,D000057934,NaN,2020,N00030780,Cory Gardner (R),United Launch Alliance,28700,0,28700,16,I,2021-03-22 00:00:00 +0000,28075080.77
16,NaN,D000022329,NaN,2020,N00030780,Cory Gardner (R),Xcel Energy,24093,4500,28593,17,I,2021-03-22 00:00:00 +0000,28075080.77
17,NaN,D000000090,NaN,2020,N00030780,Cory Gardner (R),Bank of America,18224,10000,28224,18,I,2021-03-22 00:00:00 +0000,28075080.77
18,NaN,D000000461,NaN,2020,N00030780,Cory Gardner (R),Comcast Corp,16750,10000,26750,19,I,2021-03-22 00:00:00 +0000,28075080.77
19,NaN,D000022158,NaN,2020,N00030780,Cory Gardner (R),NorPAC,26550,0,26550,20,I,2021-03-22 00:00:00 +0000,28075080.77
20,NaN,D000067823,NaN,2020,N00044206,John Hickenlooper (D),Alphabet Inc,256481,0,256481,1,C,2021-03-22 00:00:00 +0000,43012517.53
21,NaN,D000025328,NaN,2020,N00044206,John Hickenlooper (D),Democracy Engine,238166,0,238166,2,C,2021-03-22 00:00:00 +0000,43012517.53
22,NaN,D000030653,NaN,2020,N00044206,John Hickenlooper (D),University of Colorado,176333,0,176333,3,C,2021-03-22 00:00:00 +0000,43012517.53
23,NaN,D000000406,NaN,2020,N00044206,John Hickenlooper (D),University of California,172769,0,172769,4,C,2021-03-22 00:00:00 +0000,43012517.53
24,NaN,D000052457,NaN,2020,N00044206,John Hickenlooper (D),J Street,159825,85,159910,5,C,2021-03-22 00:00:00 +0000,43012517.53
25,NaN,D000000115,NaN,2020,N00044206,John Hickenlooper (D),Microsoft Corp,119505,0,119505,6,C,2021-03-22 00:00:00 +0000,43012517.53
26,NaN,D000000544,NaN,2020,N00044206,John Hickenlooper (D),Harvard University,105905,0,105905,7,C,2021-03-22 00:00:00 +0000,43012517.53
27,NaN,D000021754,NaN,2020,N00044206,John Hickenlooper (D),Apple Inc,73507,0,73507,8,C,2021-03-22 00:00:00 +0000,43012517.53
28,NaN,D000023883,NaN,2020,N00044206,John Hickenlooper (D),Amazon.com,71571,0,71571,9,C,2021-03-22 00:00:00 +0000,43012517.53
29,NaN,D000000128,NaN,2020,N00044206,John Hickenlooper (D),Walt Disney Co,67202,0,67202,10,C,2021-03-22 00:00:00 +0000,43012517.53
30,NaN,D000022300,NaN,2020,N00044206,John Hickenlooper (D),US Government,66737,0,66737,11,C,2021-03-22 00:00:00 +0000,43012517.53
31,NaN,D000033563,NaN,2020,N00044206,John Hickenlooper (D),Facebook Inc,65025,0,65025,12,C,2021-03-22 00:00:00 +0000,43012517.53
32,NaN,D000000750,NaN,2020,N00044206,John Hickenlooper (D),Stanford University,62390,0,62390,13,C,2021-03-22 00:00:00 +0000,43012517.53
33,NaN,D000000076,NaN,2020,N00044206,John Hickenlooper (D),AT&T Inc,57604,0,57604,14,C,2021-03-22 00:00:00 +0000,43012517.53
34,NaN,D000000461,NaN,2020,N00044206,John Hickenlooper (D),Comcast Corp,56641,0,56641,15,C,2021-03-22 00:00:00 +0000,43012517.53
35,NaN,D000034986,NaN,2020,N00044206,John Hickenlooper (D),Kaiser Permanente,51865,0,51865,16,C,2021-03-22 00:00:00 +0000,43012517.53
36,NaN,D000067699,NaN,2020,N00044206,John Hickenlooper (D),Liberty Media Corp,47436,0,47436,17,C,2021-03-22 00:00:00 +0000,43012517.53
37,NaN,D000000720,NaN,2020,N00044206,John Hickenlooper (D),IBM Corp,45986,0,45986,18,C,2021-03-22 00:00:00 +0000,43012517.53
38,NaN,NaN,NaN,2020,N00044206,John Hickenlooper (D),Insight Partners,43200,0,43200,19,C,2021-03-22 00:00:00 +0000,43012517.53
39,NaN,D000032757,NaN,2020,N00044206,John Hickenlooper (D),Colorado State University,42569,0,42569,20,C,2021-03-22 00:00:00 +0000,43012517.53
40,NaN,NaN,NaN,2020,N00026350,Bruce Lohmiller (3),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
41,NaN,NaN,NaN,2020,N00036864,Gaylon Kent (L),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
42,NaN,NaN,NaN,2020,N00042085,Raymon Doane (L),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
43,NaN,NaN,NaN,2020,N00045350,Veronique Bellamy (3),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
44,NaN,NaN,NaN,2020,N00045459,Joshua Rodriguez (3),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
45,NaN,NaN,NaN,2020,N00046162,Joey Camp (I),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
46,NaN,NaN,NaN,2020,N00046965,Lisa Garcia (I),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
47,NaN,NaN,NaN,2020,N00047091,Martha Wolf (I),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
48,NaN,NaN,NaN,2020,N00047829,Daniel Doyle (3),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00
49,NaN,NaN,NaN,2020,N00047831,Danny Skelly (3),NaN,0,0,0,0,C,2021-03-22 00:00:00 +0000,0.00

In [6]:
all_processed_contribs = pd.DataFrame()
for file in glob("raw_contributions/*"):
    contribs = pd.read_csv(file)
    race = file.split("/")[-1].split(".")[0]
    state = race[:2]
    processed_contribs = contribs.apply(extract_contrib, axis=1)
    processed_contribs = processed_contribs.assign(race=race)
    processed_contribs = processed_contribs.assign(state=state)
    all_processed_contribs = pd.concat([all_processed_contribs, processed_contribs])
all_processed_contribs

,firstname,lastname,party,total,individual,pac,contributor,race,state
0,cory,gardner,republican,124600,124600,0,Votesane PAC,COS2,CO
1,cory,gardner,republican,64961,52461,12500,Apollo Global Management,COS2,CO
2,cory,gardner,republican,55979,55979,0,GEO Group,COS2,CO
3,cory,gardner,republican,51765,35765,16000,Blue Cross/Blue Shield,COS2,CO
4,cory,gardner,republican,50788,50788,0,Blackstone Group,COS2,CO
...,...,...,...,...,...,...,...,...,...
38,don,bolduc,republican,2900,2900,0,Nh Leadership Pac,NHS1,NH
39,don,bolduc,republican,2900,2900,0,Nixon Peabody LLP,NHS1,NH
40,jeremy,kauffman,other,2200,2200,0,Brennan Appraisal,NHS1,NH
41,jeremy,kauffman,other,1500,1500,0,Gfy LLC,NHS1,NH
42,jeremy,kauffman,other,1000,1000,0,Dempsey Digital LLC,NHS1,NH

In [7]:
senators = pd.read_csv("S117_members.csv")

code_to_party = {100: "democrat", 200: "republican"}
def create_senator(senator):
    name = senator["bioname"]
    node_attrs = {
        "lastname": name.split(",")[0].lower(),
        "firstname": name.split(",")[1].split()[0].lower(),
        "party": code_to_party.get(senator["party_code"], "other"),
        "state": senator["state_abbrev"],
        "icpsr": senator["icpsr"]
    }
    return pd.Series(node_attrs)
senator_nodes = senators.apply(create_senator, axis=1)
senator_nodes

       lastname firstname       party state  icpsr
0         trump    donald  republican   USA  99912
1         biden    joseph    democrat   USA  99913
2    tuberville    thomas  republican    AL  42102
3        shelby   richard  republican    AL  94659
4     murkowski      lisa  republican    AK  40300
..          ...       ...         ...   ...    ...
99      manchin       joe    democrat    WV  40915
100     baldwin     tammy    democrat    WI  29940
101     johnson       ron  republican    WI  41111
102      lummis   cynthia  republican    WY  20953
103    barrasso      john  republican    WY  40707

[104 rows x 5 columns]

In [8]:
def find_icpsr(row):
    #senator = senator_nodes[senator_nodes["firstname"] == row["firstname"]]
    senator = senator_nodes[senator_nodes["lastname"] == row["lastname"]]
    senator = senator[senator_nodes["state"] == row["state"]]

    if len(senator) > 0:
        icpsr = senator.iloc[0].icpsr
    else:
        icpsr = -1
    return icpsr

all_processed_contribs["icpsr"] =  all_processed_contribs.apply(find_icpsr, axis=1)

<ipython-input-8-4d26eddf648c>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  senator = senator[senator_nodes["state"] == row["state"]]

In [9]:
all_processed_contribs[all_processed_contribs["icpsr"] != -1]

,firstname,lastname,party,total,individual,pac,contributor,race,state,icpsr
20,john,hickenlooper,democrat,256481,256481,0,Alphabet Inc,COS2,CO,42101
21,john,hickenlooper,democrat,238166,238166,0,Democracy Engine,COS2,CO,42101
22,john,hickenlooper,democrat,176333,176333,0,University of Colorado,COS2,CO,42101
23,john,hickenlooper,democrat,172769,172769,0,University of California,COS2,CO,42101
24,john,hickenlooper,democrat,159910,159825,85,J Street,COS2,CO,42101
...,...,...,...,...,...,...,...,...,...,...
15,maggie,hassan,democrat,42548,42548,0,Massachusetts Institute of Technology,NHS1,NH,41702
16,maggie,hassan,democrat,41622,33755,7867,League of Conservation Voters,NHS1,NH,41702
17,maggie,hassan,democrat,40165,40165,0,Dartmouth College,NHS1,NH,41702
18,maggie,hassan,democrat,38832,38832,0,University of New Hampshire,NHS1,NH,41702
19,maggie,hassan,democrat,38535,33535,5000,Microsoft Corp,NHS1,NH,41702

In [10]:
all_processed_contribs[all_processed_contribs["icpsr"] != -1].to_csv("contributions_with_icpsr.csv")